name: screen_config
description: Easier way to handle dynamic sizes
version: 0.1.0
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
repository: https://github.com/A-Castanho/screen_config

flutter:
  plugin:
    platforms:
      android:
        package: pt.castanho.screen_config
        pluginClass: ScreenConfigPlugin
      ios:
        pluginClass: ScreenConfigPlugin
      linux:
        pluginClass: ScreenConfigPlugin
      macos:
        pluginClass: ScreenConfigPlugin
      windows:
        pluginClass: ScreenConfigPluginCApi
